### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by DoubleTPeter** [robiot/zzCrack#3]
Tried out the updated script. And with wordlist.. got an error listed bellow.

Also i checked out bruteforce, but dident have time to wait it out. it stopped on something around 400 when i tried it. is it supposed to do that? and just takes a bit of time?

Enter a directory/name to a .zip file > test.zip
Which attack type would you like to run
0: Bruteforce    1: Wordlist > 1
[+] Enter a directory/name to a password list > rockyou.txt

Do you want to output everything (slower) or not (faster)  y/n > y
Loading Wordlist, Please wait
Traceback (most recent call last):
  File "D:\Desktop\Test\zz.py", line 308, in <module>
    main().main()
  File "D:\Desktop\Test\zz.py", line 275, in main
    self._noargs()
  File "D:\Desktop\Test\zz.py", line 202, in _noargs
    self.wlist_crack_entry(archive_dir, wordlist_inp, showoutput_b, None)
  File "D:\Desktop\Test\zz.py", line 82, in wlist_crack_entry
    wordlist = _wordlist.read().splitlines()
  File "C:\Users\peter\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5079963: invalid continuation byte

**Comment by robiot** [comment]
I got no clue about the bruteforce issue. It may be something with windows so I will check it out later!

Because it wouldn't decode the byte I added errors='ignore' so it will ignore all the errors when decoding
